### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by yaronr** [mysensors/Raspberry#26]
Hey
Great project(s)

What about creating a Docker image for Raspberry?
(Same question for MyController, etc)
That would make the installation very easy. install docker, and docker run ...
Maybe I can help, let me know if this makes any sense.

**Comment by tfyoung** [comment]
The issue with making a docker image is that this needs to both access the SPI and then provides it as a tty. I'm investigating either using tcp or mqtt for providing it but don't have anything shareable yet.

**Comment by clempat** [comment]
I personally use docker for all on my raspi: akkerman/rpi-nginx, agileek/rpi-domoticz-docker, https://gist.github.com/clempat/9ffbbf2a34928e0b175f

with domoticz the part of my docker-compose is:
```
domoticz:
  image: agileek/rpi-domoticz-docker
  restart: always
  ports:
    - "8080:8080"
  devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
  volumes:
    - "./files/domoticz.db:/root/domoticz/domoticz.db:rw"
    - "./files/domoticz:/root/domoticz/scripts:rw"
    - "/etc/localtime:/etc/localtime:ro"
```

I don't know if it helps...
